- name: Service Setup
  hosts: localhost
  become: yes

  vars:
    path_root_services: "/usr/lib/systemd"
    path_root_enabled_services: "/etc/systemd/system"

  tasks:
    - name: Systemd Service Copy
      copy:
        src: simple-ansible2cxx.service
        dest: "{{ path_root_services }}/system/simple-ansible2cxx.service"
        owner: root
        group: root
        mode: 0644
    - name: Manually enabling Systemd Service
      file:
        src: "{{ path_root_services }}/system/simple-ansible2cxx.service"
        dest: "{{ path_root_enabled_services }}/multi-user.target.wants/simple-ansible2cxx.service"
        state: link